name: My first workflow
on: [push, workflow_dispatch]

jobs:
  My-first-job: 
    run-on: ubuntu-latest
    steps:
      - run: echo "Hellow World!"
  My-second-job:
    runs-on: : ubuntu-latest
    steps:
      - run: echo "Bye World"