name: My first workflow
on: push

jobs:
  echo-hello: 
    runs-on: ubuntu-latest
    steps:
      - name: say hello
        run: echo "Hello World!"
  echo-goodbye:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Bye World"