name: 02 - Workflow Events
on: 
  push:
    pull_request:

jobs:
  echo-job:
    runs-on: ubuntu-latest 
    steps:
      - name: Show the trigger
        run: echo "I've been executed by an ${{ github.event_name }} event." 